<?php

namespace AI_Translate;

defined( 'ABSPATH' ) || exit;

/**
 * Provides the built-in model-profile definitions used by TranslationRuntime.
 */
final class ModelProfileRegistry {

	/**
	 * Return the built-in model profiles before external filters are applied.
	 */
	public static function get_default_profiles(): array {
		return array(
			array(
				'id'                         => 'translategemma',
				'matchers'                   => array( 'translategemma' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'generic_template',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => true,
				'extra_request_body'         => array(
					'chat_template_kwargs' => array(
						'source_lang_code' => '{source_lang_code}',
						'target_lang_code' => '{target_lang_code}',
					),
				),
				'chunk_strategy'             => 'default',
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => false,
					'retry_on_passthrough_de'     => false,
					'reduce_chunk_on_retry'       => false,
				),
			),
			array(
				'id'                         => 'towerinstruct',
				'matchers'                   => array( 'towerinstruct' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => false,
				'extra_request_body'         => array(),
				'chunk_strategy'             => 'tower_conservative',
				'max_chunk_chars'            => 1200,
				'temperature'                => 0.2,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1200,
				),
			),
			array(
				'id'                         => 'salamandra',
				'matchers'                   => array( 'salamandrata', 'salamandra' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => false,
				'extra_request_body'         => array(),
				'chunk_strategy'             => 'tower_conservative',
				'max_chunk_chars'            => 1200,
				'temperature'                => 0.2,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1200,
				),
			),
			array(
				'id'                         => 'madlad',
				'matchers'                   => array( 'madlad400', 'madlad-400', 'madlad' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => false,
				'supports_chat_completions'  => false,
				'extra_request_body'         => array(),
				'chunk_strategy'             => 'tower_conservative',
				'max_chunk_chars'            => 1400,
				'temperature'                => 0.2,
				'retry_profile'              => array(
					'retry_on_validation_failure' => false,
					'retry_on_passthrough_de'     => false,
					'reduce_chunk_on_retry'       => false,
				),
			),
			array(
				'id'                         => 'qwen_thinking_aware',
				'matchers'                   => array( 'qwen3.5', 'qwen3.6', 'qwen' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => true,
				'extra_request_body'         => array(
					'chat_template_kwargs' => array(
						'enable_thinking' => false,
					),
				),
				'chunk_strategy'             => 'tower_conservative',
				'max_chunk_chars'            => 2400,
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1400,
				),
			),
			array(
				'id'                         => 'glm_thinking_aware',
				'matchers'                   => array( 'glm-4.6v', 'glm' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => true,
				'extra_request_body'         => array(
					'chat_template_kwargs' => array(
						'enable_thinking' => false,
					),
				),
				'chunk_strategy'             => 'default',
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1800,
				),
			),
			array(
				'id'                         => 'gemma4_thinking_aware',
				'matchers'                   => array( 'gemma-4-e4b-it', 'gemma-4' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => true,
				'extra_request_body'         => array(
					'chat_template_kwargs' => array(
						'enable_thinking' => false,
					),
				),
				'chunk_strategy'             => 'default',
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1800,
				),
			),
			array(
				'id'                         => 'phi4_thinking_aware',
				'matchers'                   => array( 'phi-4-mini', 'phi-4', 'phi4' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => true,
				'extra_request_body'         => array(
					'chat_template_kwargs' => array(
						'enable_thinking' => false,
					),
				),
				'chunk_strategy'             => 'default',
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1800,
				),
			),
			array(
				'id'                         => 'openrouter_nemotron',
				'matchers'                   => array( 'nvidia/nemotron', 'openrouter nvidia/nemotron', 'openrouter nemotron' ),
				'request_mode'               => 'system_plus_user',
				'prompt_style'               => 'generic_template',
				'supports_system_role'       => true,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => false,
				'extra_request_body'         => array(),
				'chunk_strategy'             => 'default',
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1800,
				),
			),
			array(
				'id'                         => 'nemotron_thinking_aware',
				'matchers'                   => array( 'nemotron', 'nvidia-nemotron' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => true,
				'extra_request_body'         => array(
					'chat_template_kwargs' => array(
						'enable_thinking' => false,
					),
				),
				'chunk_strategy'             => 'default',
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1800,
				),
			),
			array(
				'id'                         => 'eurollm',
				'matchers'                   => array( 'eurollm' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => false,
				'extra_request_body'         => array(),
				'chunk_strategy'             => 'tower_conservative',
				'max_chunk_chars'            => 2600,
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1400,
				),
			),
			array(
				'id'                         => 'llama31',
				'matchers'                   => array( 'llama-3.1-8b-instruct', 'sauerkrautlm-8b-instruct', 'sauerkrautlm' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => false,
				'extra_request_body'         => array(),
				'chunk_strategy'             => 'tower_conservative',
				'max_chunk_chars'            => 2400,
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1400,
				),
			),
			array(
				'id'                         => 'ministral3',
				'matchers'                   => array( 'ministral-3-3b', 'ministral-3' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => false,
				'extra_request_body'         => array(),
				'chunk_strategy'             => 'tower_conservative',
				'max_chunk_chars'            => 2400,
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1400,
				),
			),
			array(
				'id'                         => 'ministral',
				'matchers'                   => array( 'ministral', 'ministral-8b', 'ministral-8b-instruct' ),
				'request_mode'               => 'user_only',
				'prompt_style'               => 'bilingual_frame',
				'supports_system_role'       => false,
				'requires_strict_direct_api' => false,
				'requires_chat_template_kwargs' => false,
				'extra_request_body'         => array(),
				'chunk_strategy'             => 'default',
				'temperature'                => 0,
				'retry_profile'              => array(
					'retry_on_validation_failure' => true,
					'retry_on_passthrough_de'     => true,
					'reduce_chunk_on_retry'       => true,
					'retry_chunk_chars'           => 1800,
				),
			),
		);
	}
}
